# Generated by Django 4.0.6 on 2022-10-27 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOpinionAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_categ', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=500)),
                ('user_foreign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
