# Generated by Django 4.0.6 on 2022-10-27 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_useropinionagent'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendingInsuranceAgents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=200)),
                ('org_image', models.ImageField(upload_to='org-images')),
                ('genre', models.CharField(max_length=200)),
                ('estimated_payable', models.FloatField()),
            ],
        ),
    ]
