# Generated by Django 4.0.6 on 2022-10-27 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_trendinginsuranceagents'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.CharField(max_length=100)),
                ('car_name', models.CharField(max_length=100)),
                ('interest_rate', models.FloatField()),
                ('duration', models.IntegerField()),
                ('monthly_payment', models.FloatField()),
                ('phno', models.CharField(max_length=15)),
            ],
        ),
    ]
