# Generated by Django 4.0.6 on 2022-10-27 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_carloan'),
    ]

    operations = [
        migrations.CreateModel(
            name='HousingLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=200)),
                ('interest_rate', models.FloatField()),
                ('duration', models.IntegerField()),
                ('monthly_payment', models.FloatField()),
                ('phno', models.CharField(max_length=15)),
            ],
        ),
    ]
